language: ruby

matrix:
  include:
    - name: "Rails 4.2 on Ruby 2.3.8"
      rvm: 2.3.8
      gemfile: gemfiles/rails_4.2.gemfile

    - name: "Rails 5.0 on Ruby 2.4.10"
      rvm: 2.4.10
      gemfile: gemfiles/rails_5.0.gemfile

    - name: "Rails 5.1 on Ruby 2.5.8"
      rvm: 2.5.8
      gemfile: gemfiles/rails_5.1.gemfile
    - name: "Rails 5.2 on Ruby 2.5.8"
      rvm: 2.5.8
      gemfile: gemfiles/rails_5.2.gemfile

    - name: "Rails 5.2 on Ruby 2.6.6"
      rvm: 2.6.6
      gemfile: gemfiles/rails_5.2.gemfile
    - name: "Rails 6.0 on Ruby 2.6.6"
      rvm: 2.6.6
      gemfile: gemfiles/rails_6.0.gemfile

    - name: "Rails 6.0 on Ruby 2.7.2"
      rvm: 2.7.2
      gemfile: gemfiles/rails_6.0.gemfile
    - name: "Rails 6.1 on Ruby 2.7.2"
      rvm: 2.7.2
      gemfile: gemfiles/rails_6.1.gemfile

    - name: "Rails 6.1 on Ruby 3.0.0"
      rvm: 3.0.0
      gemfile: gemfiles/rails_6.1.gemfile

    - name: "Rails 5.2 on JRuby 9.2.14.0"
      rvm: jruby-9.2.14.0
      gemfile: gemfiles/rails_5.2.gemfile
    - name: "Rails 6.0 on JRuby 9.2.14.0"
      rvm: jruby-9.2.14.0
      gemfile: gemfiles/rails_6.0.gemfile
    - name: "Rails 6.1 on JRuby 9.2.14.0"
      rvm: jruby-9.2.14.0
      gemfile: gemfiles/rails_6.1.gemfile

  allow_failures:
    - rvm: jruby-9.2.14.0

jdk:
  - openjdk9

services:
  - mongodb

sudo: false
