name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Rails ${{ matrix.rails }} on Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        include:
          - rails: 5.1
            ruby: 2.5

          - rails: 5.2
            ruby: 2.5
          - rails: 5.2
            ruby: 2.6
          - rails: 5.2
            ruby: jruby

          - rails: "6.0"
            ruby: 2.6
          - rails: "6.0"
            ruby: 2.7
          - rails: "6.0"
            ruby: "3.0"
          - rails: "6.0"
            ruby: jruby

          - rails: "6.1"
            ruby: "3.0"
          - rails: "6.1"
            ruby: jruby

          - rails: "6.1"
            ruby: "3.1"
          - rails: "7.0"
            ruby: "3.1"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Gemfile
        run: echo $BUNDLE_GEMFILE

      - name: Ruby Version
        run: ruby --version

      - name: Run Tests
        run: bundle exec rake test
